<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Aiden W. Harig">
<meta name="dcterms.date" content="2026-02-18">

<title>Competing Drivers of National Wellbeing: An Analysis of Wealth and Longevity – ds334_blog</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-6bd9cfa162949bde0a231f530c97869d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">ds334_blog</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com"> <i class="bi bi-twitter" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Competing Drivers of National Wellbeing: An Analysis of Wealth and Longevity</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">Public Health</div>
                <div class="quarto-category">Economics</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Aiden W. Harig </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">February 18, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#preface" id="toc-preface" class="nav-link active" data-scroll-target="#preface">Preface</a></li>
  <li><a href="#dataset-introduction" id="toc-dataset-introduction" class="nav-link" data-scroll-target="#dataset-introduction">Dataset Introduction</a></li>
  <li><a href="#modeling-wellbeing-as-a-function-of-gdp-per-capita" id="toc-modeling-wellbeing-as-a-function-of-gdp-per-capita" class="nav-link" data-scroll-target="#modeling-wellbeing-as-a-function-of-gdp-per-capita">Modeling Wellbeing as a Function of GDP per Capita</a></li>
  <li><a href="#modeling-wellbeing-as-a-function-of-life-expectancy" id="toc-modeling-wellbeing-as-a-function-of-life-expectancy" class="nav-link" data-scroll-target="#modeling-wellbeing-as-a-function-of-life-expectancy">Modeling Wellbeing as a Function of Life Expectancy</a></li>
  <li><a href="#addressing-nonlinearity-log-gdp-per-capita" id="toc-addressing-nonlinearity-log-gdp-per-capita" class="nav-link" data-scroll-target="#addressing-nonlinearity-log-gdp-per-capita">Addressing Nonlinearity: Log GDP per Capita</a></li>
  <li><a href="#relative-predictive-strength-of-wealth-and-longevity" id="toc-relative-predictive-strength-of-wealth-and-longevity" class="nav-link" data-scroll-target="#relative-predictive-strength-of-wealth-and-longevity">Relative Predictive Strength of Wealth and Longevity</a></li>
  <li><a href="#wrap-up-considerations-course-connection" id="toc-wrap-up-considerations-course-connection" class="nav-link" data-scroll-target="#wrap-up-considerations-course-connection">Wrap-Up, Considerations, &amp; Course Connection</a>
  <ul class="collapse">
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  <li><a href="#limitations-of-the-approach" id="toc-limitations-of-the-approach" class="nav-link" data-scroll-target="#limitations-of-the-approach">Limitations of the Approach</a></li>
  <li><a href="#future-directions" id="toc-future-directions" class="nav-link" data-scroll-target="#future-directions">Future Directions</a></li>
  <li><a href="#connecting-the-visualizations-to-course-concepts" id="toc-connecting-the-visualizations-to-course-concepts" class="nav-link" data-scroll-target="#connecting-the-visualizations-to-course-concepts">Connecting the Visualizations to Course Concepts</a></li>
  </ul></li>
  <li><a href="#citations" id="toc-citations" class="nav-link" data-scroll-target="#citations"><strong>Citations</strong></a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="preface" class="level1">
<h1>Preface</h1>
<p>What drives national wellbeing – wealth, longevity, or both?</p>
<p>Wealthier nations tend to report higher levels of happiness, but economic growth may not increase wellbeing at a constant rate. At the same time, longer life expectancy reflects improvements in health, stability, and quality of life, which may also contribute to how people evaluate their lives.</p>
<p>In this analysis, I examine how wellbeing relates to <strong>GDP per capita</strong> and <strong>Life Expectancy</strong>, first individually and then jointly. The goal is to determine whether wealth exhibits diminishing returns and whether economic prosperity or longevity plays the stronger independent role in predicting national wellbeing.</p>
<p><br></p>
<p><img src="wellbeing.jpg" class="img-fluid"></p>
<p><br><br></p>
</section>
<section id="dataset-introduction" class="level1">
<h1>Dataset Introduction</h1>
<p>This analysis uses a dataset from the <a href="https://happyplanetindex.org/"><strong>Happy Planet Index</strong></a>(<code>hpi</code>) containing cross-national indicators of wellbeing, economic output, and longevity at a single point in time.</p>
<p>The primary variables of interest are <strong>Wellbeing</strong>, measured as a national wellbeing index, <strong>GDP per capita</strong>, representing economic output per person, and <strong>Life Expectancy</strong>, representing average years of life within a country. For the purposes of this analysis, GDP per capita is examined both in its raw form and in a log-adjusted form (<code>gdp_adj</code>) to account for nonlinearity and potential diminishing marginal returns to wealth.</p>
<p>The dataset includes <strong>151 observations</strong>, corresponding to individual countries. Because the data are cross-sectional rather than longitudinal, the analysis focuses on differences across nations rather than changes over time.</p>
<p>The central question of interest is whether – and to what extent – national wealth and longevity independently predict wellbeing. Specifically, this analysis investigates whether economic prosperity exhibits diminishing returns and whether wealth or life expectancy plays the stronger role once both are considered simultaneously.</p>
<p>Finally, it is important to note that GDP per capita and life expectancy are broad proxies for development. While they capture economic and health dimensions of national conditions, they do not fully account for institutional quality, cultural factors, or social cohesion. As such, the goal of this analysis is to evaluate statistical association rather than to claim causal determination.</p>
<p><br><br><br><br></p>
</section>
<section id="modeling-wellbeing-as-a-function-of-gdp-per-capita" class="level1">
<h1>Modeling Wellbeing as a Function of GDP per Capita</h1>
<p>To begin, I model national wellbeing as a function of GDP per capita to evaluate the baseline relationship between economic prosperity and happiness. GDP per capita serves as a proxy for material wealth, allowing us to assess whether richer nations systematically report higher levels of wellbeing.</p>
<p><br></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 19%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">term</th>
<th style="text-align: center;">estimate</th>
<th style="text-align: center;">std.error</th>
<th style="text-align: center;">statistic</th>
<th style="text-align: center;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">(Intercept)</td>
<td style="text-align: center;">4.662</td>
<td style="text-align: center;">0.09232</td>
<td style="text-align: center;">50.5</td>
<td style="text-align: center;">1.266e-95</td>
</tr>
<tr class="even">
<td style="text-align: center;">GDPcapita</td>
<td style="text-align: center;">5.019e-05</td>
<td style="text-align: center;">4.24e-06</td>
<td style="text-align: center;">11.84</td>
<td style="text-align: center;">3.32e-23</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><br></p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Pearson’s product-moment correlation: <code>hpi$Wellbeing</code> and <code>hpi$GDPcapita</code></caption>
<colgroup>
<col style="width: 22%">
<col style="width: 8%">
<col style="width: 22%">
<col style="width: 33%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Test statistic</th>
<th style="text-align: center;">df</th>
<th style="text-align: center;">P value</th>
<th style="text-align: center;">Alternative hypothesis</th>
<th style="text-align: center;">cor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">11.84</td>
<td style="text-align: center;">149</td>
<td style="text-align: center;">3.32e-23 * * *</td>
<td style="text-align: center;">two.sided</td>
<td style="text-align: center;">0.6962</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><br></p>
<blockquote class="blockquote">
<p>The results indicate a strong positive association between GDP per capita and wellbeing <strong>(r = 0.696, p &lt; &gt;.001)</strong>, suggesting that wealthier nations tend to report higher happiness levels. However, the scatterplot &gt;reveals noticeable curvature – particularly at lower income levels – where gains in GDP appear to produce &gt;larger increases in wellbeing than at higher levels of wealth. This pattern raises the possibility that the &gt;relationship may not be linear, motivating further examination of potential diminishing returns. [1]</p>
</blockquote>
<p><br><br><br><br></p>
</section>
<section id="modeling-wellbeing-as-a-function-of-life-expectancy" class="level1">
<h1>Modeling Wellbeing as a Function of Life Expectancy</h1>
<p>Next, I examine whether national wellbeing is associated with life expectancy. Life expectancy serves as a broad indicator of population health, healthcare access, and overall social development. This model evaluates whether countries where people live longer also report higher levels of wellbeing.</p>
<p><br></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 23%">
<col style="width: 15%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">term</th>
<th style="text-align: center;">estimate</th>
<th style="text-align: center;">std.error</th>
<th style="text-align: center;">statistic</th>
<th style="text-align: center;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">(Intercept)</td>
<td style="text-align: center;">-0.4891</td>
<td style="text-align: center;">0.4876</td>
<td style="text-align: center;">-1.003</td>
<td style="text-align: center;">0.3174</td>
</tr>
<tr class="even">
<td style="text-align: center;">LifeExpectancy</td>
<td style="text-align: center;">0.08425</td>
<td style="text-align: center;">0.006916</td>
<td style="text-align: center;">12.18</td>
<td style="text-align: center;">3.963e-24</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><br></p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Pearson’s product-moment correlation: <code>hpi$Wellbeing</code> and <code>hpi$LifeExpectancy</code></caption>
<colgroup>
<col style="width: 22%">
<col style="width: 8%">
<col style="width: 24%">
<col style="width: 33%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Test statistic</th>
<th style="text-align: center;">df</th>
<th style="text-align: center;">P value</th>
<th style="text-align: center;">Alternative hypothesis</th>
<th style="text-align: center;">cor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">12.18</td>
<td style="text-align: center;">149</td>
<td style="text-align: center;">3.963e-24 * * *</td>
<td style="text-align: center;">two.sided</td>
<td style="text-align: center;">0.7064</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><br></p>
<blockquote class="blockquote">
<p>The results show a strong positive relationship between life expectancy and wellbeing <strong>(r = 0.706, p &lt; .001)</strong>, indicating that nations with longer average lifespans tend to report higher happiness levels. The scatterplot suggests a fairly linear association, with wellbeing increasing steadily as life expectancy rises. Unlike GDP per capita, there is less visible curvature in this relationship, suggesting more consistent returns to improvements in longevity.</p>
</blockquote>
<p><br><br><br><br></p>
</section>
<section id="addressing-nonlinearity-log-gdp-per-capita" class="level1">
<h1>Addressing Nonlinearity: Log GDP per Capita</h1>
<p>The initial GDP model suggested that the relationship between wealth and wellbeing may not be strictly linear. To address this potential nonlinearity, GDP per capita is log-transformed, allowing the model to better capture possible diminishing returns to wellbeing. This adjustment helps determine whether the strength of the association changes once the curvature in the data is accounted for.</p>
<p><br></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><br></p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 19%">
<col style="width: 15%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">term</th>
<th style="text-align: center;">estimate</th>
<th style="text-align: center;">std.error</th>
<th style="text-align: center;">statistic</th>
<th style="text-align: center;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">(Intercept)</td>
<td style="text-align: center;">-0.3771</td>
<td style="text-align: center;">0.4404</td>
<td style="text-align: center;">-0.8563</td>
<td style="text-align: center;">0.3932</td>
</tr>
<tr class="even">
<td style="text-align: center;">gdp_adj</td>
<td style="text-align: center;">0.65</td>
<td style="text-align: center;">0.04907</td>
<td style="text-align: center;">13.25</td>
<td style="text-align: center;">5.765e-27</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><br></p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Pearson’s product-moment correlation: <code>hpi$Wellbeing</code> and <code>hpi$gdp_adj</code></caption>
<colgroup>
<col style="width: 22%">
<col style="width: 8%">
<col style="width: 24%">
<col style="width: 33%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Test statistic</th>
<th style="text-align: center;">df</th>
<th style="text-align: center;">P value</th>
<th style="text-align: center;">Alternative hypothesis</th>
<th style="text-align: center;">cor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">13.25</td>
<td style="text-align: center;">149</td>
<td style="text-align: center;">5.765e-27 * * *</td>
<td style="text-align: center;">two.sided</td>
<td style="text-align: center;">0.7354</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><br></p>
<blockquote class="blockquote">
<p>After log-adjusting GDP per capita, the relationship with wellbeing remains strong <strong>(r = 0.735, p &lt; .001)</strong> and appears more linear. The improved fit supports the idea of diminishing marginal returns, where increases in income are associated with larger gains in wellbeing at lower levels of wealth and smaller gains at higher levels. This transformation provides a more accurate representation of how economic prosperity relates to national happiness.</p>
</blockquote>
<p><br><br><br><br></p>
</section>
<section id="relative-predictive-strength-of-wealth-and-longevity" class="level1">
<h1>Relative Predictive Strength of Wealth and Longevity</h1>
<p>To determine whether wealth or longevity plays the stronger role in predicting wellbeing, both variables are included simultaneously in a standardized regression model. Standardizing the predictors allows for direct comparison of their relative effects, as each coefficient reflects the expected change in wellbeing associated with a one standard deviation increase in the predictor. This approach compares the independent contribution of economic prosperity and life expectancy.</p>
<p><br></p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 33%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">term</th>
<th style="text-align: center;">estimate</th>
<th style="text-align: center;">std.error</th>
<th style="text-align: center;">statistic</th>
<th style="text-align: center;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">(Intercept)</td>
<td style="text-align: center;">7.501e-16</td>
<td style="text-align: center;">0.05385</td>
<td style="text-align: center;">1.393e-14</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">scale(gdp_adj)</td>
<td style="text-align: center;">0.482</td>
<td style="text-align: center;">0.09927</td>
<td style="text-align: center;">4.856</td>
<td style="text-align: center;">3.014e-06</td>
</tr>
<tr class="odd">
<td style="text-align: center;">scale(LifeExpectancy)</td>
<td style="text-align: center;">0.3021</td>
<td style="text-align: center;">0.09927</td>
<td style="text-align: center;">3.043</td>
<td style="text-align: center;">0.002774</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><br></p>
<blockquote class="blockquote">
<p>Both log-adjusted GDP and life expectancy remain statistically significant predictors of wellbeing when modeled together. However, the standardized coefficient for <strong>GDP (β = 0.482)</strong> exceeds that of <strong>life expectancy (β = 0.302)</strong>, indicating that wealth exerts a stronger independent association with national wellbeing after accounting for longevity. While health and longevity clearly matter, economic prosperity appears to play the more dominant role in explaining cross-national differences in happiness. [2]</p>
</blockquote>
<p><br><br><br><br></p>
</section>
<section id="wrap-up-considerations-course-connection" class="level1">
<h1>Wrap-Up, Considerations, &amp; Course Connection</h1>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>Across models, both national wealth and life expectancy exhibit strong positive associations with wellbeing. The baseline results show that richer and longer-living nations tend to report higher happiness levels. However, adjusting GDP per capita for nonlinearity reveals evidence of diminishing marginal returns – suggesting that gains in wellbeing are larger at lower levels of income and taper off as countries become wealthier. When both predictors are examined simultaneously, each remains statistically significant, but standardized results indicate that economic prosperity exerts the stronger independent association with national wellbeing.</p>
<p>Together, the findings suggest that both wealth and longevity contribute meaningfully to cross-national differences in happiness, but income – particularly at lower levels of development – plays a slightly more dominant role.</p>
</section>
<section id="limitations-of-the-approach" class="level2">
<h2 class="anchored" data-anchor-id="limitations-of-the-approach">Limitations of the Approach</h2>
<p>Several limitations should be acknowledged. First, the analysis is cross-sectional, meaning it compares countries at a single point in time rather than examining changes within countries over time. Second, GDP per capita and life expectancy are broad proxies for development and may capture overlapping institutional and social factors, such as governance quality, education, inequality, or political stability. Omitted variable bias may therefore influence the relationships. Finally, while the log transformation addresses nonlinearity in GDP, the models remain relatively simple and assume linear relationships after adjustment.</p>
</section>
<section id="future-directions" class="level2">
<h2 class="anchored" data-anchor-id="future-directions">Future Directions</h2>
<p>With additional data or time, several extensions could strengthen the analysis. A longitudinal dataset would allow for examining how changes in wealth or life expectancy within a country affect changes in wellbeing over time. Incorporating additional predictors – such as income inequality, education levels, political freedom, or social dynamics – could help disentangle the mechanisms through which development influences happiness. Finally, exploring interaction effects between wealth and longevity may reveal whether the relationship between income and wellbeing differs across levels of health development.</p>
</section>
<section id="connecting-the-visualizations-to-course-concepts" class="level2">
<h2 class="anchored" data-anchor-id="connecting-the-visualizations-to-course-concepts">Connecting the Visualizations to Course Concepts</h2>
<p>The visualizations in this analysis are effective because they align with several core principles of good data communication discussed in class.</p>
<p>First, the use of <strong>scatterplots</strong> is appropriate for displaying relationships between two quantitative variables. Scatterplots preserve individual data points, allowing the reader to see distribution, clustering, spread, and potential outliers rather than just summary statistics. This supports transparency and avoids hiding variation.</p>
<p>Second, the addition of <strong>fitted regression lines</strong> enhances interpretability. Rather than requiring readers to infer trends visually, the line makes the direction and strength of association clear. This supports the principle of reducing cognitive load for readers.</p>
<p>Third, the visualizations use <strong>minimalist design choices</strong> (consistent axes, limited color palette, clean theme), which reduce clutter and keep attention focused on the data. The consistent formatting across sections also supports comparison between models.</p>
<p>Finally, the progression of visuals – from raw GDP, to life expectancy, to log-adjusted GDP, to standardized comparison – creates a <strong>clear analytical narrative</strong>. Rather than presenting isolated charts, the sequence guides the reader through a logical modeling process. This aligns with the idea that effective visualizations do not only display data, but tell a structured story.</p>
<p><br><br><br><br></p>
</section>
</section>
<section id="citations" class="level1">
<h1><strong>Citations</strong></h1>
<p>[1] B. Abel, “Is there a way to put code blocks in block quotes?,” <em>Meta Stack Overflow</em>, Jan.&nbsp;06, 2016. https://meta.stackoverflow.com/questions/314122/is-there-a-way-to-put-code-blocks-in-block-quotes</p>
<p>[2] M. Alexander, “Standardized regression coefficients using lm() and scale() differ from those using lm.beta() or cor(),” Stack Overflow. https://stackoverflow.com/questions/39158119/standardized-regression-coefficients-using-lm-and-scale-differ-from-those-us</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>